### ISSUE TITLE
NullPointerException: Missing required view with ID

### ISSUE THREAD

**Issue by phongbm** [okcredit/CoroutineLayoutInflater#6]
I use this library, with some layout I get error: `NullPointerException: Missing required view with ID`.
I don't understand where the error is. How to fix that?

**Comment by anjalsaneen** [comment]
Could you please provide more details about your layout? Please let me know if you are able to inflate the view with normal LayoutInflater.from(context).inflate?

**Comment by anjalsaneen** [comment]
If you bind a view to the wrong layout, you will receive an error stating that it cannot find the expected child views. Closing this ticket due to inactivity. Please feel free to reopen it if you can provide more details.
